package de.ryoshi.minigame.model;

public enum MessageType {
    MOVE,
    STOP_MOVE,
    GAME_STATE,
    LEFT,
    JOIN,
    SHOOT,
    DELETE_BULLET,
    PLAYER_HIT,
    SPAWN,
    KILLED,
    HEAL,
    REACTIVATE_HEAL,
    EVENT,
    END_GAME,
    TIMER,
    VIEW_ANGLE,
    STOP_EVENT,
    CHANGE_WEAPON,
    SHOTGUN_SHOT,
    SPAWN_POWERUP,
    TAKE_POWERUP,
    USE_POWERUP,
    TOWER,
}
